name: dart2java
version: 0.2.0
description: >
  Experimental Dart to Java compiler designed to create idiomatic, readable Java
  output.

author: Dart Dev Compiler team <dev-compiler@dartlang.org>
homepage: https://github.com/dart-lang/dev_compiler

dependencies:
  analyzer: ^0.28.0-alpha.1
  args: ^0.13.0
  bazel_worker: ^0.1.0
  cli_util: ^0.0.1
  func: ^0.1.0
  html: ^0.12.0
  js: ^0.6.0
  kernel:
    # This is an old modified version of Kernel
    # TODO(springerm): Use newer version of Kernel, it probably has everything
    # that we implemented in our version by now.
    git: 
      url: ssh://git@github.com/google/dart2java.git
      ref: kernel
  path: ^1.3.0
  pub_semver: ^1.1.0
  source_maps: ^0.10.0
  source_span: ^1.0.2

dependency_overrides:
  analyzer: ^0.28.0-alpha.1

dev_dependencies:
  # We pin a specific version to ensure everyone is formatting the code exactly
  # the same way. This is because any change in dart_style, even non-breaking
  # changes, may change the output format.
  dart_style: 0.2.4
  test: ^0.12.0
  unittest: ^0.11.6
  webdriver: ^1.1.0

environment:
  sdk: ">=1.12.0 <2.0.0"

executables:
  dart2java: dart2java
  dumptree: dumptree
